
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h5 class="modal-title"><?php $this->language->_e("Add/Edit Partner") ?></h5>
</div>

<form id="member-form" class="form-horizontal" onsubmit="formSubmit();
        return false;" action="#">
          <?php
          if (isset($data["pa_id"]))
          {
              ?>
        <input type="hidden" name="data[pa_id]" value="<?php echo $data["pa_id"]; ?>" />
        <?php
    }
    ?>
    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-sm-2"><?php echo $this->language->_e("Name"); ?></label>
            <label class="control-label col-sm-4">    <input placeholder="Enter Partner Name" require="true" name="data[pa_name]" value="<?php
                if (isset($data["pa_name"]))
                {
                    echo $data["pa_name"];
                }
                ?>"  class="form-control" type="text"></label>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-link" data-dismiss="modal"><?php $this->language->_e("Close") ?></button>
        <button type="submit" class="btn btn-primary"><?php $this->language->_e("Save") ?></button>
    </div>
</form>
<script>
    function formSubmit()
    {
        HQMain.ajax(rootUrl + "partner/save-partner", $("#member-form").serialize());
        return false;
    }

</script>