<script type="text/javascript">
    var rootUrl = "<?php echo $this->url->get($this->module_config->main_route); ?>/";
    var HQLanguage = {
        ajax_fail_message: "<?php $this->language->_e("Action Failed . Please Contact Admin"); ?>",
        ajax_success_title: "<?php $this->language->_e("Success"); ?>",
        ajax_fail_title: "<?php $this->language->_e("Error"); ?>",
        ajax_cancel_title: "<?php $this->language->_e("Cancel"); ?>",
        ajax_delete_title: "<?php $this->language->_e("Are you sure to delete it ?"); ?>"
    };
</script>