<div class="page-header">
    <h1>Congratulations!</h1>
</div>
<p>You're now flying with Phalcon. Great things are about to happen!</p>

<em>CoreCore</em>
<p><?php $this->language->_e("Dm English :"); ?></p>
<p><?php $this->holders->load("Core_Side_Bar", "Index", "index"); ?></p>
<form action="?language=vi">
    <input type="submit" value="tieng viet" />
</form>
<form action="?language=en">
    <input type="submit" value=" tieng anh" />
</form>