<?php $admin = $this->session->get("admin"); ?>
<div class="sidebar sidebar-main">
    <div class="sidebar-content">

        <!-- User menu -->
        <div class="sidebar-user">
            <div class="category-content">
                <div class="media">
                    <a class="media-left" href="#"><img alt="" class="img-circle img-sm" src="<?php echo $this->url->getStatic("img/temp/placeholder.jpg"); ?>"></a>
                    <div class="media-body">
                        <span class="media-heading text-semibold"><?php echo $admin["mv_nickname"] ?></span>
                    </div>

                    <div class="media-right media-middle">
                        <ul class="icons-list">
                            <li>
                                <a href="#"><i class="icon-cog3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- /user menu -->


        <!-- Main navigation -->
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">
                <ul class="navigation navigation-main navigation-accordion">

                    <!-- Main -->
                    <li class="navigation-header">
                        <span><?php $this->language->_e("Main") ?></span> 
                        <i title="" class="icon-menu" data-original-title="Main pages"></i>
                    </li>
                    <li class="active"><a href="<?php echo $this->url->get($this->module_config_bgame->main_route); ?>"><i class="icon-home4"></i> <span><?php $this->language->_e("Dashboard") ?></span></a></li>
                    <?php
                    if (\HqEngine\HqTool\HqUtil::checkPermission("user", $admin["mv_permission"]))
                    {
                        ?>
                        <li class="navigation-header"><span><?php $this->language->_e("User") ?></span> <i data-original-title="Forms" class="icon-menu" title=""></i></li>
                        <li>
                            <a href="#" class="has-ul"><i class="icon-copy"></i> <span><?php $this->language->_e("User Management") ?></span></a>
                            <ul class="hidden-ul">
                                <li><a href="<?php echo $this->url->get($this->module_config_bgame->main_route . "/member") ?>"><?php $this->language->_e("List User") ?></a></li>
                            </ul>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <!-- /main navigation -->

    </div>
</div>