<!-- Page container -->
<div class="page-container login-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Content area -->
            <div class="content">

                <!-- Simple login form -->
                <form id="admin-login-form"  action="" submit="return false;">
                    <div id="login-form" class="panel panel-body login-form">
                        <div class="text-center">
                            <div class="icon-object border-slate-300 text-slate-300"><i class="icon-reading"></i></div>
                            <h5 class="content-group"><?php $this->language->_e("Login to your account "); ?><small class="display-block"><?php $this->language->_e("Enter your credentials below"); ?></small></h5>
                        </div>

                        <div class="form-group has-feedback has-feedback-left">
                            <input name="username" type="text" class="form-control" placeholder="<?php $this->language->_e("Username"); ?>">
                            <div class="form-control-feedback">
                                <i class="icon-user text-muted"></i>
                            </div>
                        </div>

                        <div class="form-group has-feedback has-feedback-left">
                            <input name="password" type="password" class="form-control" placeholder="<?php $this->language->_e("Password"); ?>">
                            <div class="form-control-feedback">
                                <i class="icon-lock2 text-muted"></i>
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="button" onclick="loginForm();" class="btn btn-primary btn-block"><?php $this->language->_e("Sign in"); ?> <i class="icon-circle-right2 position-right"></i></button>
                        </div>
                    </div>
                </form>
                <!-- /simple login form -->

            </div>
            <!-- /content area -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>
<!-- /page container -->
<script>
    function loginForm()
    {
        HQMain.ajax(rootUrl + "access/login", $("#admin-login-form").serialize(), function () {
            window.location.href = rootUrl;
        });
    }
</script>